export const data = {
    "login": "tassioFront",
    "id": 47509510,
    "node_id": "MDQ6VXNlcjQ3NTA5NTEw",
    "avatar_url": "https://avatars.githubusercontent.com/u/47509510?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/tassioFront",
    "html_url": "https://github.com/tassioFront",
    "followers_url": "https://api.github.com/users/tassioFront/followers",
    "following_url": "https://api.github.com/users/tassioFront/following{/other_user}",
    "gists_url": "https://api.github.com/users/tassioFront/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/tassioFront/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/tassioFront/subscriptions",
    "organizations_url": "https://api.github.com/users/tassioFront/orgs",
    "repos_url": "https://api.github.com/users/tassioFront/repos",
    "events_url": "https://api.github.com/users/tassioFront/events{/privacy}",
    "received_events_url": "https://api.github.com/users/tassioFront/received_events",
    "type": "User",
    "site_admin": false,
    "name": "Tássio",
    "company": "@juntossomosmais",
    "blog": "",
    "location": "Brazil",
    "email": null,
    "hireable": null,
    "bio": "I'm FrontEnd Developer that loves wine and coffee. ☕️🍷👨🏻‍💻",
    "twitter_username": null,
    "public_repos": 39,
    "public_gists": 0,
    "followers": 27,
    "following": 38,
    "created_at": "2019-02-10T23:25:10Z",
    "updated_at": "2021-07-14T17:20:54Z"
}